# use Java and non-root
dist: trusty
sudo: true
language: Java
jdk: oraclejdk8

# ignore the virtualenv that Travis creates
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# install all dependencies
before_install:
  #install mdl for readme markdown linting, proselint to check readme, htmlhint
  #to check src.
  - gem install mdl
  - npm install htmlhint -g
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install proselint
  - pip install pipenv
  # do not allow Travis to use standard error for debugging purposes
  - unset _JAVA_OPTIONS

script:
  # lint the assignment's documentation
  - mdl README.md
  - proselint README.md
  - htmlhint site/content\surveyPage.html
  - htmlhint site/content\contact.html
  - htmlhint site/content/post\first.html
  - htmlhint site/content/post\second.html
  - htmlhint site/static/admin/index.html
