baseurl = "/"
languageCode = "en-us"
title = "AssistMe"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 2
canonifyurls = true
[[menu.main]]
identifier = "blog"
name = "Download Page"
url = "/"
weight = -120
[[menu.main]]
name = "Survey"
url = "/surveyPage"
weight = 100
[[menu.main]]
name = "Github repos"
pre = "<h3>Site Repo</h3>"
url = "https://github.com/JattMones/assist-me-download.netlify.com"
weight = 102
[[menu.main]]
name = "Contact"
pre = "<h3>Contact me</h3>"
url = "/contact"
weight = 109

[params]
  description = "Click to Download"
  cover = "images/techProgress2.jpg"
  author = "Matt Jones"
  authorlocation = "USA"
  authorwebsite = "http://mattjonesofficial.netlify.com"
  bio= "my bio"
  logo = "images/logo.jpg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "Allegheny-CS-SeniorThesis-2018/cmpsc-600-610-project-3-2018-2019-allegheny-college-JattMones"
  githubName2 = "jattMones"
  #twitterName = "vjeantet"
  # facebookName = ""
  linkedinName = "theofficialmattjones"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"
